yet another try at packaging

diff --git a/fedora/canl-java-tomcat.spec.in b/fedora/canl-java-tomcat.spec.in
--- a/fedora/canl-java-tomcat.spec.in
+++ b/fedora/canl-java-tomcat.spec.in
@@ -49,7 +49,12 @@ rm -rf $RPM_BUILD_ROOT
 %doc README.md doc/RELEASE-NOTES doc/COPYRIGHT doc/LICENSE doc/USAGE
 
 %post
-if [ @@TOMCAT@@x == "tomcat5x" ] ; then
+if [ x%{?dist} == xel6 ]; then
+	tomcat_ver = tomcat6
+else
+	tomcat_ver = tomcat5
+fi	
+if [ ${tomcat_ver}x == "tomcat5x" ] ; then
 	ln -sn %{_datadir}/java/%{name}.jar /var/lib/tomcat5/server/lib/[%{name}].jar
 	if [ -f /usr/share/java/bcprov.jar ] ; then 
 		ln -snf /usr/share/java/bcprov.jar /var/lib/tomcat5/server/lib/[bcprov].jar
@@ -66,7 +71,7 @@ if [ @@TOMCAT@@x == "tomcat5x" ] ; then
 	else
 		echo /usr/share/java/canl-java.jar not found, cannot link it to the tomcat server/lib
 	fi
-elif [ @@TOMCAT@@x == "tomcat6x" ] ; then
+elif [ ${tomcat_ver}x == "tomcat6x" ] ; then
 	ln -sn %{_datadir}/java/%{name}.jar /usr/share/tomcat6/lib/[%{name}].jar
 	if [ -f /usr/share/java/bcprov.jar ] ; then 
 		ln -snf /usr/share/java/bcprov.jar /usr/share/tomcat6/lib/[bcprov].jar
@@ -82,7 +87,7 @@ elif [ @@TOMCAT@@x == "tomcat6x" ] ; then
 		echo /usr/share/java/canl-java.jar not found, cannot link it to the tomcat server/lib
 	fi
 else
-	echo "invalid tomcat setting "@@TOMCAT@@", not linking jars to it's server/lib" >&2
+	echo "invalid tomcat setting "${tomcat_ver}", not linking jars to it's server/lib" >&2
 fi
 
 
